### ISSUE TITLE
Investigate SOLR

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/ckanext-nhm#204]
Can we move datastore search to SOLR?  
Test performance.
Do we need a dedicated SOLR box? 
SQL search? Investigate SOLR sql-like query language.

**Comment by aliceh75** [comment]
Solr can return the data in a variety of format, including json, python and csv (there is no Python library to read the solr binary format). We are interested in finding what is the best format for our purposes: fetch a single field (an id) and return a list of values along with the total number of matching records. The id field may be an integer or a string. Both are being tested here.

Notes:
- The csv format doesn't return the total number of matching rows, so we have to run two queries, one to get the total and one to get the rows;
- we tested with the python standard json library and with usjon

100*3*26 iterations (filter searches on ft and field), download 100 rows of _id:

- ujson: 27.65
- json: 28.3
- python: 33
- csv: 33.47

10*3*26 iterations (filter searches on ft and field), download 5000 rows of _id:

- ujson: 97.62
- json: 99.35
- python: 125
- csv: 125.69

100*3*26 iterations (filter searches on ft and field), download 100 rows of occurrenceID:

- ujson: 28.35
- json: 31.44
- python: 36.09
- csv: 36.71

10*3*26 iterations (filter searches on ft and field), download 5000 rows of occurrenceID:

- ujson: 112.56
- json: 117.17
- python: 134.37
- csv: 134.50

Result: json is always the fastest format, and ujson provides a small advantage over json.

**Comment by aliceh75** [comment]
Indexing wise, it took about 30mn to index 2.7m rows on our staging server. This takes several hours when done using Postgres.

**Comment by aliceh75** [comment]
Ideally, we want to use solr for searching but keep the data itself in Postgresql - as this is where ckan stores it, and we'd have to rewrite a complete datastore extension if we wanted to store the data elsewhere.

So the question is: is it faster to use postgresql to do the search and return the data, or use solr to do the search, get the ids, then use those to get the data from postgresql.

Here is a test performing queries on 10,000 test words (randomly extracted from the database itself) and returning the full row of data. The solr version also returns the total number of matching rows, while the Postgresql version doesn't (so there would be an extra cost for this).

                                                        | solr query + fetch from postgres | postgres only
---------------------------------------------|------------------------------------------| -----------------
avg request time for full text search | 0.0538802690029                      |  0.856008695507
avg request time for wildcard search within field | 0.135742911911     | 0.55673145299

This was run on the staging server, with Postgres having a full text index and a btree index on the searched field. Note that these numbers should not be taken at face value - the increases seen here might not apply once the same setup is applied to our production environment which has different demands than the staging one has. However these results are a good indication that this is a route worth pursuing.

**Comment by aliceh75** [comment]
For the record, one of the reason this makes sense is that solr is a more specialized tool for the job at hand. Postgres is good at it's job, but there's a lot of features we don't actually need. Postgres provides relational data and joins, which we don't need (flat table). Postgres provides real time indexing and searches always reflect the exact state of the data - which is something we can live without (our data is updated one a week, and while entries may be added few changes are expected). 

There would be a case to be made for not using Postgres at all - and keeping the data in a key/value store (or maybe in solr?), however as mentioned previously this would require a full rewrite of a datastore extension.

**Comment by aliceh75** [comment]
I've been testing the geospatial search with Solr. I am noticing that when doing a polygon search in a busy region we are not getting exactly the same results as we did with Postgis. This may be due how edges are interpreted (inclusive/exclusive), or floating point differences. Needs some more investigation. For info here is the polygon I've been searching against:

```
_geom:"Intersects(POLYGON ((-7.91015625 49.83798245308484, 3.1640625 49.724479188713005, 3.1640625 55.07836723201515, -4.74609375 58.99531118795094, -12.3046875 57.89149735271031, -14.23828125 52.26815737376817, -7.91015625 49.83798245308484))) distErrPct=0"
```

**Comment by aliceh75** [comment]
The datastore provides an SQL API. The point is to provide an API that allows users to analyse, not just query, the data - ie. apply group bys, sums, etc. and get the result. Can we provide anything similar with Solr?

It seems heliosearch aim to provide an sql parser for solr - http://heliosearch.org/heliosearch-sql-sub-project/ - though I don't think that's something we can easily re-use. It is possible to do joins with solr ( https://wiki.apache.org/solr/Join ) and to use functions ( https://cwiki.apache.org/confluence/display/solr/Function+Queries ) - so we could implement a simple analysis functionality.

Our options would be:

1. To implement a subset of sql, parse that and generate a Solr query with joins and functions;
2. To provide a different API that allows users to use Solr analysis functionality;
3. To allow users to use the datastore sql API, but limit it's usage to, say, one request at a time;
4. Store the data in a different database that provides faster analysis tools;
5. Not provide a data analysis API.

I think 1 and 4 would be a lot of work, and not worth the effort. 2 would it still be a bit of work, and I'm worried we'd be stretching solr into different directions. The point of using Solr in the first place is to use a specialized search engine for performance. Trying to use it as an analysis engine might well loose the benefits.

I think we should consider search and analysis separately, and thus 3 is a better option. However such queries would be very slow to run on our production server (because we will be getting rid of the indexes in Postgres).

So really I would opt for 5. We don't have the resources to allow external users to run analysis of our data. They can still use our search from their scripts - so only doing the actual calculations locally.

@benscott what do you think?

**Comment by aliceh75** [comment]
So after discussion we decided to leave data analysis for now. Performance is more important at the moment, and we will come back to it once we have a fast search api.

So this means we can answer the questions raised in the issue:
To answer the questions asked in the initial issue:

- Can we move datastore search to SOLR?

    I think we can answer "yes", in as much as all searches we do with Postgresql can be done with SOLR.

- Test performance.

    Performance tests have been done (see previous notes), and indicate that it's likely we would have performance increase. An additional point not previously noted is the increased performance in updating the dataset. At the moment, to get any performance out of Postgres, we have a lot of different indexes (because our users do searches on a lot of different fields). This causes extremely slow updates, as all the indexes need to be updated. So using solr also means we'd have less indexes, and improved update times.

- Do we need a dedicated SOLR box? 

    Difficult to answer for now, but I assume not. We are going to free up a lot of Postgres resources which can be allocated to Solr.

- SQL search? Investigate SOLR sql-like query language.

    Not currently possible to offer either SQL like syntax, or generally data analysis.


So we are ready to start actually implementing a solr search extension. This has been started to some extent for the purpose of testing. I will close this issue and open one for the implentation (which was the intended purpose).
