### ISSUE TITLE
Allow multiple image fields

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/ckanext-nhm#315]
At present only one image field can be displayed.

**Comment by jrdh** [comment]
Hey @edwbaker, I've just dev'd up a delimiter input for the image field that's been selected so that users can provide a list of images in the image field they've selected. This was something @essvee requested alongside this issue, however, I was wondering whether this change solves the issue you were having or whether you were looking for the ability to specify multiple image fields? If so that's different and I'll not close this issue when I merge the other PR.
