### ISSUE TITLE
Index Lots

### ISSUE THREAD

**Issue by edwbaker** [NaturalHistoryMuseum/ckanext-nhm#388]
Considering that most species within the entomology collection only exist under the Index Lots collection, it would make sense to include these in search results.

I have had to review a paper recently where people assumed type specimens were lost because they did not turn up in the main search results, even though there were details in the Index Lots collection.

**Comment by jrdh** [comment]
The solution for this issue (cross-resource searching) is on our roadmap, has been since the beginning of the year and has a high priority. However, it requires an overhaul of the backend search services before it is possible to expose this functionality on the site. This overhaul is in the design stages at the moment and won't be implemented and released for at least 2 - 3 months due to other higher priority items and the length of time this work will take to complete. Rest assured it will happen, just not immediately. We certainly want to avoid the scenarios like the one you describe and make the site easier to use for the unfamiliar.

**Comment by jrdh** [comment]
I'll attach this issue to the milestones once they get created so that you can track progress :slightly_smiling_face:

**Comment by jrdh** [comment]
This is now complete. With the release of integrated searching on the Data Portal you can search across multiple resources at the same time so searching on the specimens and index lots is now possible.
