### ISSUE TITLE
Requesting “Content-Type: application/rdf+xml” results in 404 (not found) instead of getting RDF

### ISSUE THREAD

**Issue by infinite-dao** [NaturalHistoryMuseum/ckanext-nhm#458]
**Description**
Trying a request with the header “`Accept: application/rdf+xml`” will get an RDF file, but requesting it via the header “`Content-Type: application/rdf+xml`” results in 404 (not found), which is unexpected. 

My guess is, that this is actually a server communication problem, but I don’t know where I should better report the error.

**Expected Behaviour**
Request by header “`Accept: application/rdf+xml`” and/or header “`Content-Type: application/rdf+xml`” will get an RDF file.

**To Reproduce**
The following `wget` command results in 404 (not found):
    
    wget --header='Content-Type: application/rdf+xml' "https://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724/1581984000000"
    wget --header='Accept: application/rdf+xml' --header='Content-Type: application/rdf+xml' "https://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724/1581984000000"

The following `wget` command results in 200 (OK):
    
    wget --header='Accept: application/rdf+xml' "https://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724/1581984000000"

**Error Log**
```
--2020-02-18 12:24:15-- https://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724/1581984000000
CA certificate "/etc/ssl/certs/ca-certificates.crt" was loaded
Resolving the host name data.nhm.ac.uk (data.nhm.ac.uk)... 64.113.50.62
Establishing a connection to data.nhm.ac.uk (data.nhm.ac.uk)|64.113.50.62|:443 ...
HTTP request sent, waiting for response ... 404 Not Found
2020-02-18 12:24:15 ERROR 404: Not Found.
```

**Comment by jrdh** [comment]
Hi @infinite-dao, thanks for reporting this. I believe, as you suggested, that this is indeed a communication problem, specifically with our firewall. If you use `curl` to make the request you'll see that there is actually a body returned along with the 404 status code: 

```
curl -H 'Content-Type: application/rdf+xml' "https://data.nhm.ac.uk/object/8846cc56-b2f3-4e0a-9a43-6c75dfd27724/1581984000000"
```

and the body is one of our firewall's default block pages, for example (we're working with our firewall provider to hopefully make these less aggressive-looking in the future!):

![image](https://user-images.githubusercontent.com/4718259/74739392-a528d780-5250-11ea-9551-16c6a4a032e4.png)

I'm waiting on confirmation from our firewall team here at the museum as to the reason for the block, but I think it is because there's a `Content-Type` header on a `GET` request  and they're only useful on `POST`s or `PUT`s so there's no reason to accept the request and pass it on to the backend. It's a bit odd that it `404`s, perhaps a status code of `400` would be more sensible. I'm not sure whether that is something we can configure in the firewall though but I'll try and find out.

Is there a reason why you were including the `Content-Type` header in your `GET` requests in the first place or were you just playing around and noticed some potentially odd behaviour?

Thanks!

**Comment by jrdh** [comment]
Quick additional thing, you can also use the `--content-on-error` flag with `wget` if you can't/don't want to use `curl`.

**Comment by infinite-dao** [comment]
> Is there a reason why you were including the `Content-Type` header in your `GET` requests in the first place or were you just playing around and noticed some potentially odd behaviour?

Well, yes and I must confess I did not think it through with the headers. Now I see because the [`Content-Type` documentation (on developer.mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) states clearly this is the media type of the (returned) _resource_ or POSTed _resource_ and hence the header `Content-Type` has no meaning in my request from its definition point of view ;-) So I will omit it in my request.

**Comment by jrdh** [comment]
No worries @infinite-dao, I had to look it up in the Mozilla docs too! :tada:
